'use client';
import { useEffect, useState } from 'react';
export type RecipientValidationStatus='empty'|'checking'|'valid'|'invalid'|'unsupported'|'unavailable';
export interface RecipientValidation { status:RecipientValidationStatus; resolvedAddress:string|null; message:string|null; passport:boolean; }
const EVM=/^0x[a-fA-F0-9]{40}$/; const PASSPORT=/^[a-z0-9_-]{3,32}(?:\.arc)?$/i; const FOREIGN=/^(?:0x)?[0-9a-fA-F]{64}$/;
export function useRecipientValidation(value:string):RecipientValidation{
 const [state,setState]=useState<RecipientValidation>({status:'empty',resolvedAddress:null,message:null,passport:false});
 useEffect(()=>{let cancelled=false;const input=value.trim();setState({status:'empty',resolvedAddress:null,message:null,passport:false});if(!input)return; if(EVM.test(input)){setState({status:'valid',resolvedAddress:input,message:'Valid Arc-compatible EVM address',passport:false});return;} if(FOREIGN.test(input)||/^(?:sol|sui|bc1|addr1)/i.test(input)){setState({status:'unsupported',resolvedAddress:null,message:'This address format is not supported on Arc.',passport:false});return;} if(!PASSPORT.test(input)){setState({status:'invalid',resolvedAddress:null,message:'Enter a valid EVM address or .arc Passport.',passport:false});return;} const username=input.toLowerCase().replace(/\.arc$/,'');setState({status:'checking',resolvedAddress:null,message:'Verifying Passport…',passport:true});const timer=window.setTimeout(async()=>{try{const response=await fetch(`/api/passport/resolve?username=${encodeURIComponent(username)}`);let data:{walletAddress?:string;error?:string}={};try{data=await response.json();}catch{}if(cancelled)return;if(!response.ok||!data.walletAddress){setState({status:'unavailable',resolvedAddress:null,message:data.error||'Passport could not be verified right now.',passport:true});return;}if(!EVM.test(data.walletAddress)){setState({status:'unavailable',resolvedAddress:null,message:'Passport resolution returned an invalid wallet address.',passport:true});return;}setState({status:'valid',resolvedAddress:data.walletAddress,message:`Verified Passport ${username}.arc`,passport:true});}catch{if(!cancelled)setState({status:'unavailable',resolvedAddress:null,message:'Passport verification is unavailable. Try again.',passport:true});}},250);return()=>{cancelled=true;window.clearTimeout(timer)};},[value]);return state;
}
