'use client';
import { useState,useCallback,useRef } from 'react';
import { useWaitForTransactionReceipt,useAccount } from 'wagmi';
import { createViemAdapterFromProvider } from '@circle-fin/adapter-viem-v2';
import { AppKit } from '@circle-fin/app-kit';
import { createPublicClient,formatEther,formatUnits,http,parseUnits } from 'viem';
import { PRIMARY_CONTRACT,PRIMARY_DECIMALS,ERC20_ABI,CHAIN_ID,RPC_URL } from '@/lib/contracts';
import { useAppStore } from '@/lib/store';
import { parseTransactionError,generateId } from '@/lib/utils';
import { announceTransactionState } from '@/lib/transaction/voice';
import toast from 'react-hot-toast';
import type { TransactionRecord } from '@/types';
interface TransferParams{to:string;amount:string;note?:string}
const EVM=/^0x[a-fA-F0-9]{40}$/; const HASH=/^0x[0-9a-fA-F]{64}$/; const PASSPORT=/^[a-z0-9_-]{3,32}(?:\.arc)?$/i;
async function resolveRecipient(value:string){const v=value.trim();if(EVM.test(v))return v;if(!PASSPORT.test(v))throw new Error('Recipient is not a valid Arc-compatible EVM address or .arc Passport.');const username=v.toLowerCase().replace(/\.arc$/,'');announceTransactionState('preflight');const r=await fetch(`/api/passport/resolve?username=${encodeURIComponent(username)}`);let d:{walletAddress?:string;error?:string}={};try{d=await r.json()}catch{}if(!r.ok||!d.walletAddress)throw new Error(d.error||`Passport ${username}.arc is unavailable.`);if(!EVM.test(d.walletAddress))throw new Error('Passport resolution returned an invalid wallet address.');return d.walletAddress;}
async function preflight(address:`0x${string}`,amount:string){const c=createPublicClient({transport:http(RPC_URL)});const req=parseUnits(amount,PRIMARY_DECIMALS);const[native,gas,usdc]=await Promise.all([c.getBalance({address}),c.getGasPrice(),c.readContract({address:PRIMARY_CONTRACT,abi:ERC20_ABI,functionName:'balanceOf',args:[address]})]);if(usdc<req)throw new Error(`Insufficient USDC. You have ${formatUnits(usdc,PRIMARY_DECIMALS)} USDC, but ${amount} USDC is required. No transaction was submitted.`);const needed=gas*100_000n*2n;if(native<needed)throw new Error(`Insufficient ARC for network fees. Approximately ${formatEther(needed)} ARC is required. No USDC was sent.`)}
async function record(payload:Record<string,unknown>){try{const r=await fetch('/api/transfer/record',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)return null;return ((await r.json()) as{id?:string}).id??null}catch{return null}}
function patch(payload:Record<string,unknown>){void fetch('/api/transfer/record',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).catch(()=>{})}
export function useTransfer(mode:TransactionRecord['mode']='manual'){
 const{address,connector}=useAccount();const{addTransaction,updateTransaction}=useAppStore();const[isPending,setPending]=useState(false),[isSuccess,setSuccess]=useState(false),[error,setError]=useState<string|null>(null),[txHash,setTxHash]=useState<`0x${string}`>();const localId=useRef<string|null>(null),docId=useRef<string|null>(null);
 const{isLoading:isConfirming,isSuccess:receiptSuccess,isError:receiptError}=useWaitForTransactionReceipt({hash:txHash,query:{enabled:!!txHash}});
 if(receiptSuccess&&txHash&&localId.current&&!isSuccess){setSuccess(true);setPending(false);updateTransaction(localId.current,{status:'confirmed',txHash});patch({docId:docId.current,status:'confirmed',txHash});toast.dismiss(txHash);toast.success('Transfer confirmed on Arc');announceTransactionState('confirmed');}
 if(receiptError&&txHash&&localId.current&&!isSuccess){setPending(false);updateTransaction(localId.current,{status:'failed',txHash});patch({docId:docId.current,status:'failed',txHash});toast.dismiss(txHash);toast.error('Transaction failed on-chain');announceTransactionState('failed');}
 const transfer=useCallback(async({to,amount,note}:TransferParams)=>{if(!address||!connector){setError('Wallet not connected');return}if(isPending)return;setError(null);setSuccess(false);setTxHash(undefined);setPending(true);const id=generateId();localId.current=id;try{announceTransactionState('preflight');const resolved=await resolveRecipient(to);await preflight(address,amount);addTransaction({id,walletAddress:address,toAddress:resolved,amount:parseUnits(amount,PRIMARY_DECIMALS).toString(),amountFormatted:amount,status:'pending',token:'USDC',chainId:CHAIN_ID,createdAt:new Date().toISOString(),note,mode,type:'send'});const d=await record({walletAddress:address,toAddress:resolved,amount:parseUnits(amount,PRIMARY_DECIMALS).toString(),amountFormatted:amount,token:'USDC',note,mode});docId.current=d;announceTransactionState('wallet_approval');const provider=await connector.getProvider();const adapter=await createViemAdapterFromProvider({provider:provider as never});const kit=new AppKit();const result=await kit.send({from:{adapter,chain:'Arc_Testnet' as const},to:resolved,amount,token:'USDC' as const});const hash=result.txHash as `0x${string}`;if(!HASH.test(hash))throw new Error('Arc App Kit returned no valid transaction hash');setTxHash(hash);updateTransaction(id,{txHash:hash});patch({docId:d,status:'pending',txHash:hash});toast.success('Transaction submitted');announceTransactionState('submitted');announceTransactionState('pending');}catch(e){const msg=parseTransactionError(e);setError(msg);setPending(false);updateTransaction(id,{status:'failed'});patch({docId:docId.current,status:'failed',log:{level:'error',message:'Transfer failed',data:{error:msg},walletAddress:address}});toast.error(msg);announceTransactionState('failed');}},[address,connector,addTransaction,updateTransaction,isPending,mode]);
 const reset=useCallback(()=>{setPending(false);setSuccess(false);setError(null);setTxHash(undefined);localId.current=null;docId.current=null},[]);return{transfer,isPending,isConfirming,isSuccess,isError:!!error,error,txHash:txHash??null,reset};
}
